# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#

dependencies:
  cache_directories:
    - "~/.apt-cache"
  pre:
    - sudo rm -rf /var/cache/apt/archives && sudo ln -s ~/.apt-cache /var/cache/apt/archives && mkdir -p ~/.apt-cache/partial

apt-run: &apt-install
  name: install system packages
  command: |
    sudo apt update -qq
    sudo apt install -y python-pip
    sudo pip install ansible
    sudo pip install --upgrade setuptools

version: 2.1

executors:
  content-executor:
    docker:
      - image: circleci/python:latest
    working_directory: ~/repo

jobs:
  validate-app:
    executor: content-executor
    steps:
      - run:
          name: checkout repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "" ]; then
                git clone https://${GITHUB_TOKEN}@github.com/it-kombinat/Splunk_TA_nix.git
            else
                git clone --branch ${CIRCLE_BRANCH} https://${GITHUB_TOKEN}@github.com/it-kombinat/Splunk_TA_nix.git
            fi
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Splunk_TA_nix/default/app.conf" }}
      - run: *apt-install
      - run:
          name: grab appinspect
          command: |
            curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o appinspect-lastest.tar.gz
            mkdir appinspect-latest
            tar -zxvf appinspect-lastest.tar.gz -C appinspect-latest --strip-components=1
      - run:
          name: install appinspect
          command: |
            cd appinspect-latest
            rm -rf venv
            sudo pip install --upgrade pip setuptools
            sudo pip install virtualenv
            virtualenv --python=/usr/bin/python2.7 --clear venv
            source venv/bin/activate
            pip install .
      - run:
          name: run appinspect
          command: |
            rm -rf Splunk_TA_nix/.git
            rm -rf Splunk_TA_nix/.circleci
            rm -rf Splunk_TA_nix/.gitignore
            tar -zcvf Splunk_TA_nix.tar.gz Splunk_TA_nix
            mkdir dist
            cp Splunk_TA_nix.tar.gz dist/
            cd appinspect-latest
            source venv/bin/activate
            splunk-appinspect inspect ../Splunk_TA_nix.tar.gz --included-tags=cloud 
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Splunk_TA_nix/default/app.conf" }}
          paths:
            - "venv"
      - persist_to_workspace:
          root: dist/
          paths:
              - Splunk_TA_nix.tar.gz
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - attach_workspace:
          at: ~/dist/Splunk_TA_nix.tar.gz
      - run:
          name: publish release on github
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ~/dist/Splunk_TA_nix.tar.gz
  deploy-new-release:
    executor: content-executor
    steps:
      - run:
          name: Ansible Play
          command: |
            ansible --version
    
workflows:
  version: 2.1
  validate-and-build:
    jobs:
      - validate-app:
          filters:
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - validate-app
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - deploy-new-release:
          requires:
            - validate-app
          filters:
            tags:
              only: /.*/
